name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - develop


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Java 21 사용
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew  # gradlew 파일에 실행 권한 추가

      - name: Build with Gradle
        run: ./gradlew clean build -x test # 테스트 제외하고 빌드. 필요시 '-x test' 제거 가능

      - name: List build directory
        run: ls -l build/libs

      - name: Copy jar file via SSH
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST_BLUE }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_BLUE }}
          source: "build/libs/munecting-deploy-0.0.1-SNAPSHOT.jar"  # 빌드된 Spring Boot jar 파일 경로
          target: "/home/ubuntu/munecting.jar"  # EC2 인스턴스의 위치

      - name: Execute remote command via SSH to start app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pkill -f 'java -jar' || true  # 기존 Spring Boot 앱이 있다면 종료
            nohup java -jar /home/ubuntu/munecting.jar > /dev/null 2>&1 &
