name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # Java 21 사용
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Copy file via SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/libs/munecting.jar"
        target: "/home/ubuntu/your-app.jar"

    - name: Execute remote command via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pkill -f 'java -jar' || true
          nohup java -jar /home/ubuntu/your-app.jar > /dev/null 2>&1 &
